id: ADF7D29C2
title: Prayer of Aspiration Towards Sukhāvatī
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:33:04.132487
  last_modified_at: 2022-03-01 01:33:04.132494
